CREATE TABLE IF NOT EXISTS items (
  id VARCHAR(26) PRIMARY KEY NOT NULL,
  name VARCHAR(30) NOT NULL,
  category VARCHAR(25) NULL,
  price INT NOT NULL,
  image_url TEXT NOT NULL,
  merchant_id VARCHAR(26) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
